In [1]:
import numpy as np
import pandas as pd
import scipy as stats
import seaborn as sns
import pandas_profiling
import matplotlib  as plt


import numpy
from sklearn import linear_model
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
import statistics as stat
from sklearn.model_selection import train_test_split

In [18]:
iris=datasets.load_breast_cancer()
iris.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [19]:
x=iris.data[:,[0,2]]
y=iris.target

In [20]:
print(x.shape)
print(y.shape)

(569, 2)
(569,)


In [21]:
list(iris.target_names)

['malignant', 'benign']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)

In [23]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(426, 2)
(426,)
(143, 2)
(143,)


In [24]:
# A simple average ensemble model
model1 = DecisionTreeClassifier(max_depth=4)
model2 = KNeighborsClassifier(n_neighbors=7)
model3 = SVC(kernel='rbf',probability=True)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [25]:
# lets look at the accuracy for each model
score1=model1.score(x_test,y_test)
print(score1)

0.8461538461538461


In [26]:
# lets look at the accuracy for each model
score2=model2.score(x_test,y_test)
print(score2)

0.8321678321678322


In [27]:
# lets look at the accuracy for each model
score3=model3.score(x_test,y_test)
print(score3)

0.8601398601398601


In [28]:
# prediciton process
pred1=model1.predict(x_test)
pred2=model2.predict(x_test)
pred3=model3.predict(x_test)

In [29]:
final_pred=np.array([])
for i in range(0,len(x_test)):
    final_pred=np.append(final_pred,stat.mode([pred1[i],
                                              pred2[i],
                                              pred3[i]]))
final_pred

array([1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1.])

In [30]:
total=np.sum(y_test==final_pred)
print("accuracy",total,"/",len(final_pred),"*100=","{0:.3f}".format(total/len(final_pred)*100),"%")

accuracy 124 / 143 *100= 86.713 %


In [31]:
#soft voting in python
spred1=model1.predict_proba(x_test)
spred2=model2.predict_proba(x_test)
spred3=model3.predict_proba(x_test)
finalpred=(spred1+spred2+spred3)/3
finalpred

array([[4.97410009e-01, 5.02589991e-01],
       [2.17225201e-01, 7.82774799e-01],
       [4.49481267e-02, 9.55051873e-01],
       [9.95341899e-01, 4.65810086e-03],
       [4.74018989e-01, 5.25981011e-01],
       [5.35933931e-01, 4.64066069e-01],
       [9.98152441e-01, 1.84755920e-03],
       [9.94445037e-01, 5.55496324e-03],
       [5.24553861e-03, 9.94754461e-01],
       [4.74091353e-01, 5.25908647e-01],
       [7.07176291e-03, 9.92928237e-01],
       [3.01239573e-01, 6.98760427e-01],
       [9.77396781e-01, 2.26032185e-02],
       [3.17003637e-02, 9.68299636e-01],
       [4.88009835e-01, 5.11990165e-01],
       [5.13237365e-02, 9.48676263e-01],
       [2.96404052e-02, 9.70359595e-01],
       [2.57306493e-02, 9.74269351e-01],
       [6.64161559e-03, 9.93358384e-01],
       [9.98842469e-01, 1.15753148e-03],
       [3.98756300e-02, 9.60124370e-01],
       [2.42776542e-02, 9.75722346e-01],
       [9.98374963e-01, 1.62503661e-03],
       [8.98965787e-02, 9.10103421e-01],
       [5.323963

In [32]:
final_class=finalpred.argmax(axis=-1)
final_class


array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [33]:
# we can applay for the volting process
emodel=VotingClassifier(estimators=[('dt',model1),('knn',model2),('svc',model3)],voting='soft')
emodel.fit(x_train,y_train)

VotingClassifier(estimators=[('dt',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=4,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_state=None,
      

In [34]:
#accuracy score for the ensemble modelis
escore=emodel.score(x_test,y_test)
print(escore)

0.8811188811188811


In [35]:
emodel.classes_

array([0, 1])