In [1]:
import numpy as np
import pandas as pd
import scipy as stats
import seaborn as sns
import pandas_profiling
import matplotlib.pyplot as plt

In [8]:
data=pd.read_csv('https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/Fruits.csv')

In [9]:
data.head(2)

Color  Weight(g)   Size Fruits
0   Red         70  Small  Apple
1   Red        100    Big  Apple

In [18]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

#convert string labels into number
color_encoded=le.fit_transform(data.Color)
print(data.Color)
print(color_encoded)

0        Red
1        Red
2     Orange
3        Red
4      Green
5        Red
6        Red
7      Green
8      Green
9        Red
10     Green
11       Red
12       Red
13       Red
14       Red
15       Red
16    Orange
17       Red
18    Orange
19       Red
20       Red
21       Red
22       Red
23     Green
24    Orange
25       Red
26     Green
27     Green
28       Red
29       Red
Name: Color, dtype: object
[2 2 1 2 0 2 2 0 0 2 0 2 2 2 2 2 1 2 1 2 2 2 2 0 1 2 0 0 2 2]


In [19]:
#convert string labels into number
color_encoded1=le.fit_transform(data.Fruits)
print(data.Fruits)
print(color_encoded1)

0      Apple
1      Apple
2      Plums
3     Cherry
4      Apple
5      Apple
6     Cherry
7      Apple
8      Apple
9     Cherry
10     Plums
11    Cherry
12     Plums
13    Cherry
14     Apple
15     Plums
16     Plums
17    Cherry
18     Plums
19    Cherry
20     Apple
21    Cherry
22    Cherry
23     Apple
24     Plums
25    Cherry
26     Plums
27     Apple
28     Plums
29     Plums
Name: Fruits, dtype: object
[0 0 2 1 0 0 1 0 0 1 2 1 2 1 0 2 2 1 2 1 0 1 1 0 2 1 2 0 2 2]


In [20]:
color_encoded2=le.fit_transform(data.Size)
print(data.Size)
print(color_encoded2)

0      Small
1        Big
2     Medium
3      Small
4        Big
5        Big
6      Small
7      Small
8      Small
9      Small
10    Medium
11     Small
12    Medium
13     Small
14     Small
15    Medium
16    Medium
17     Small
18    Medium
19     Small
20       Big
21     Small
22     Small
23     Small
24    Medium
25     Small
26    Medium
27       Big
28    Medium
29    Medium
Name: Size, dtype: object
[2 0 1 2 0 0 2 2 2 2 1 2 1 2 2 1 1 2 1 2 0 2 2 2 1 2 1 0 1 1]


In [44]:
weight=data['Weight(g)']

In [47]:
features=list(zip(color_encoded,weight,color_encoded2))
features=np.array(features,dtype=np.float)
features

array([[  2.,  70.,   2.],
       [  2., 100.,   0.],
       [  1.,  28.,   1.],
       [  2.,   3.,   2.],
       [  0., 100.,   0.],
       [  2., 100.,   0.],
       [  2.,   3.,   2.],
       [  0.,  70.,   2.],
       [  0.,  70.,   2.],
       [  2.,   7.,   2.],
       [  0.,  27.,   1.],
       [  2.,   7.,   2.],
       [  2.,  28.,   1.],
       [  2.,   7.,   2.],
       [  2.,  70.,   2.],
       [  2.,  27.,   1.],
       [  1.,  28.,   1.],
       [  2.,   3.,   2.],
       [  1.,  28.,   1.],
       [  2.,   7.,   2.],
       [  2., 100.,   0.],
       [  2.,   3.,   2.],
       [  2.,   7.,   2.],
       [  0.,  70.,   2.],
       [  1.,  28.,   1.],
       [  2.,   7.,   2.],
       [  0.,  28.,   1.],
       [  0., 100.,   0.],
       [  2.,  27.,   1.],
       [  2.,  27.,   1.]])

In [50]:
#target or label
label=le.fit_transform(color_encoded1)
print(color_encoded1)
label

[0 0 2 1 0 0 1 0 0 1 2 1 2 1 0 2 2 1 2 1 0 1 1 0 2 1 2 0 2 2]


array([0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 1,
       1, 0, 2, 1, 2, 0, 2, 2])

In [51]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
#Trining the model using the trining set
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [52]:
model.classes_

array([0, 1, 2])

In [53]:
#predicting the fruits
predicted=model.predict([[1,2,1]])
print(predicted)

[1]


In [54]:
model.score(features,label)

1.0

In [55]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7,metric='euclidean')
#Trining the model using the trining set
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [56]:
model.classes_

array([0, 1, 2])

In [57]:
#predicting the fruits
predicted=model.predict([[1,2,1]])
print(predicted)

[1]


In [59]:
model.score(features,label)

1.0