In [1]:
import numpy as np
import pandas as pd
import scipy as stats
import seaborn as sns
import pandas_profiling
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/Weather.csv')

In [3]:
data.head(2)

Outlook Temp Humidity Windy Play  Unnamed: 5
0   Rainy  Hot     High     f   no         NaN
1   Rainy  Hot     High     t   no         NaN

In [5]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

#convert string labels into number
outlook=le.fit_transform(data.Outlook)
print(data.Outlook)
print(outlook)

0        Rainy
1        Rainy
2     Overcast
3        Sunny
4        Sunny
5        Sunny
6     Overcast
7        Rainy
8        Rainy
9        Sunny
10       Rainy
11    Overcast
12    Overcast
13       Sunny
Name: Outlook, dtype: object
[1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [6]:
temp=le.fit_transform(data.Temp)
print(data.Temp)
print(temp)

0      Hot
1      Hot
2      Hot
3     Mild
4     Cool
5     Cool
6     Cool
7     Mild
8     Cool
9     Mild
10    Mild
11    Mild
12     Hot
13    Mild
Name: Temp, dtype: object
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [7]:
humidity=le.fit_transform(data.Humidity)
print(data.Humidity)
print(humidity)

0       High
1       High
2       High
3       High
4     Normal
5     Normal
6     Normal
7       High
8     Normal
9     Normal
10    Normal
11      High
12    Normal
13      High
Name: Humidity, dtype: object
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [9]:
windy=le.fit_transform(data.Windy)
print(data.Windy)
print(windy)

0     f
1     t
2     f
3     f
4     f
5     t
6     t
7     f
8     f
9     f
10    t
11    t
12    f
13    t
Name: Windy, dtype: object
[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [10]:
play=le.fit_transform(data.Play)
print(data.Play)
print(play)

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: Play, dtype: object
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [11]:
features=list(zip(outlook,windy,humidity,temp))
features=np.array(features,dtype=np.float)
features

array([[1., 0., 0., 1.],
       [1., 1., 0., 1.],
       [0., 0., 0., 1.],
       [2., 0., 0., 2.],
       [2., 0., 1., 0.],
       [2., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 2.],
       [1., 0., 1., 0.],
       [2., 0., 1., 2.],
       [1., 1., 1., 2.],
       [0., 1., 0., 2.],
       [0., 0., 1., 1.],
       [2., 1., 0., 2.]])

In [12]:
#target or label
label=le.fit_transform(play)
print(play)
label

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [13]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
#Trining the model using the trining set
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [14]:
model.classes_

array([0, 1])

In [30]:
#predicting the fruits
predicted=model.predict([[02., 0., 1., 2.]])
print(predicted)

[1]


In [31]:
model.score(features,label)

0.7857142857142857

In [32]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=10,metric='euclidean')
#Trining the model using the trining set
model.fit(features,label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [33]:
model.classes_

array([0, 1])

In [35]:
predicted=model.predict([[1., 0., 0., 1.]])
print(predicted)

[1]


In [36]:
model.score(features,label)

0.7857142857142857