In [1]:
import numpy as np
import pandas as pd
import pandas_profiling 
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Repository-DataSets/master/Regression/wiki4HE.csv')

In [3]:
data

Unnamed: 0  AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION  \
0             0   40       0      2    1       14           1            2   
1             1   42       0      5    1       18           1            2   
2             2   37       0      4    1       13           1            3   
3             3   40       0      4    0       13           1            3   
4             4   51       0      6    0        8           1            3   
..          ...  ...     ...    ...  ...      ...         ...          ...   
908         908   43       0      5    1       21           2            ?   
909         909   53       0      6    0       25           2            ?   
910         910   39       0      5    1        9           2            ?   
911         911   40       0      3    1       10           2            ?   
912         912   41       1      3    1       12           2            ?   

    OTHER_POSITION OTHERSTATUS  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3  \
0                ?           ?  ...   3    5    5    5    5    4    4    4   
1                ?           ?  ...   2    4    4    3    4    2    2    4   
2                ?           ?  ...   1    5    3    5    5    2    2    2   
3                ?           ?  ...   3    3    4    4    3    4    4    3   
4                ?           ?  ...   5    5    5    4    4    5    5    5   
..             ...         ...  ...  ..  ...  ...  ...  ...  ...  ...  ...   
908              ?           2  ...   2    2    2    2    2    ?    ?    ?   
909              ?           6  ...   4    4    3    3    4    4    4    4   
910              ?           4  ...   2    5    4    3    ?    5    5    5   
911              ?           2  ...   5    1    5    2    2    4    4    2   
912              ?           2  ...   3    3    ?    3    3    2    3    3   

    Exp4 Exp5  
0      1    2  
1      2    4  
2      1    3  
3      3    4  
4      4    4  
..   ...  ...  
908    ?    ?  
909    1    1  
910    4    1  
911    1    1  
912    1    1  

[913 rows x 54 columns]

In [6]:
data.columns

Index(['Unnamed: 0', 'AGE', 'GENDER', 'DOMAIN', 'PhD', 'YEARSEXP',
       'UNIVERSITY', 'UOC_POSITION', 'OTHER_POSITION', 'OTHERSTATUS',
       'USERWIKI', 'PU1', 'PU2', 'PU3', 'PEU1', 'PEU2', 'PEU3', 'ENJ1', 'ENJ2',
       'Qu1', 'Qu2', 'Qu3', 'Qu4', 'Qu5', 'Vis1', 'Vis2', 'Vis3', 'Im1', 'Im2',
       'Im3', 'SA1', 'SA2', 'SA3', 'Use1', 'Use2', 'Use3', 'Use4', 'Use5',
       'Pf1', 'Pf2', 'Pf3', 'JR1', 'JR2', 'BI1', 'BI2', 'Inc1', 'Inc2', 'Inc3',
       'Inc4', 'Exp1', 'Exp2', 'Exp3', 'Exp4', 'Exp5'],
      dtype='object')

In [13]:
data1=data.drop('Unnamed: 0',axis=1)

In [106]:
x_data=data2[['GENDER','DOMAIN','PhD','YEARSEXP','UNIVERSITY','UOC_POSITION','OTHER_POSITION','OTHERSTATUS','USERWIKI','PU1', 'PU2', 'PU3', 'PEU1', 'PEU2', 'PEU3', 'ENJ1', 'ENJ2',
       'Qu1', 'Qu2', 'Qu3', 'Qu4', 'Qu5', 'Vis1', 'Vis2', 'Vis3', 'Im1', 'Im2','Im3', 'SA1', 'SA2', 'SA3', 'Use1', 'Use2', 'Use3', 'Use4', 'Use5',
       'Pf1', 'Pf2', 'Pf3', 'JR1', 'JR2', 'BI1', 'BI2', 'Inc1', 'Inc2', 'Inc3','Inc4', 'Exp1', 'Exp2', 'Exp3', 'Exp4', 'Exp5']]

In [105]:
y_data=data2[['AGE']]

In [16]:
data1.isna().sum()

AGE               0
GENDER            0
DOMAIN            0
PhD               0
YEARSEXP          0
UNIVERSITY        0
UOC_POSITION      0
OTHER_POSITION    0
OTHERSTATUS       0
USERWIKI          0
PU1               0
PU2               0
PU3               0
PEU1              0
PEU2              0
PEU3              0
ENJ1              0
ENJ2              0
Qu1               0
Qu2               0
Qu3               0
Qu4               0
Qu5               0
Vis1              0
Vis2              0
Vis3              0
Im1               0
Im2               0
Im3               0
SA1               0
SA2               0
SA3               0
Use1              0
Use2              0
Use3              0
Use4              0
Use5              0
Pf1               0
Pf2               0
Pf3               0
JR1               0
JR2               0
BI1               0
BI2               0
Inc1              0
Inc2              0
Inc3              0
Inc4              0
Exp1              0
Exp2              0


In [19]:
data1['GENDER'].unique()

array([0, 1])

In [20]:
data1['DOMAIN'].unique()

array(['2', '5', '4', '6', '1', '3', '?'], dtype=object)

In [21]:
data1['PhD'].unique()

array([1, 0])

In [23]:
data1['YEARSEXP'].unique()

array(['14', '18', '13', '8', '17', '11', '12', '25', '15', '20', '5',
       '10', '9', '6', '?', '7', '36', '19', '4', '2', '23', '16', '3',
       '22', '24', '21', '1', '35', '27', '26', '30', '28', '0', '37',
       '43', '31', '39'], dtype=object)

In [24]:
data1['UNIVERSITY'].unique()

array([1, 2])

In [25]:
data1['OTHERSTATUS'].unique()

array(['?', '7', '3', '2', '6', '4', '1', '5'], dtype=object)

In [26]:
data1['OTHER_POSITION'].unique()

array(['?', '2', '1'], dtype=object)

In [27]:
data1['USERWIKI'].unique()

array(['0', '1', '?'], dtype=object)

In [93]:
data['AGE'].unique()

array([40, 42, 37, 51, 47, 43, 55, 54, 50, 48, 38, 56, 44, 39, 33, 36, 45,
       35, 41, 49, 46, 34, 59, 32, 52, 31, 62, 53, 29, 30, 57, 58, 63, 68,
       69, 24, 28, 60, 26, 64, 67, 65, 27, 23, 25, 61])

In [22]:
data1

AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION OTHER_POSITION  \
0     40       0      2    1       14           1            2              ?   
1     42       0      5    1       18           1            2              ?   
2     37       0      4    1       13           1            3              ?   
3     40       0      4    0       13           1            3              ?   
4     51       0      6    0        8           1            3              ?   
..   ...     ...    ...  ...      ...         ...          ...            ...   
908   43       0      5    1       21           2            ?              ?   
909   53       0      6    0       25           2            ?              ?   
910   39       0      5    1        9           2            ?              ?   
911   40       0      3    1       10           2            ?              ?   
912   41       1      3    1       12           2            ?              ?   

    OTHERSTATUS USERWIKI  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3 Exp4 Exp5  
0             ?        0  ...   3    5    5    5    5    4    4    4    1    2  
1             ?        0  ...   2    4    4    3    4    2    2    4    2    4  
2             ?        0  ...   1    5    3    5    5    2    2    2    1    3  
3             ?        0  ...   3    3    4    4    3    4    4    3    3    4  
4             ?        1  ...   5    5    5    4    4    5    5    5    4    4  
..          ...      ...  ...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  
908           2        0  ...   2    2    2    2    2    ?    ?    ?    ?    ?  
909           6        0  ...   4    4    3    3    4    4    4    4    1    1  
910           4        0  ...   2    5    4    3    ?    5    5    5    4    1  
911           2        0  ...   5    1    5    2    2    4    4    2    1    1  
912           2        0  ...   3    3    ?    3    3    2    3    3    1    1  

[913 rows x 53 columns]

In [29]:
data1.tail(350)

AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION OTHER_POSITION  \
563   52       1      1    0       11           1            6              2   
564   40       1      6    0        9           1            6              2   
565   40       1      6    0        5           1            6              1   
566   42       1      6    0        6           1            6              1   
567   49       1      1    0        5           1            6              2   
..   ...     ...    ...  ...      ...         ...          ...            ...   
908   43       0      5    1       21           2            ?              ?   
909   53       0      6    0       25           2            ?              ?   
910   39       0      5    1        9           2            ?              ?   
911   40       0      3    1       10           2            ?              ?   
912   41       1      3    1       12           2            ?              ?   

    OTHERSTATUS USERWIKI  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3 Exp4 Exp5  
563           ?        0  ...   2    3    2    2    2    2    3    3    3    5  
564           ?        0  ...   5    ?    ?    ?    ?    5    5    5    1    1  
565           7        0  ...   2    4    4    4    4    2    3    1    1    1  
566           7        0  ...   3    4    4    2    3    3    3    2    1    2  
567           ?        0  ...   3    4    5    5    3    3    4    4    1    1  
..          ...      ...  ...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  
908           2        0  ...   2    2    2    2    2    ?    ?    ?    ?    ?  
909           6        0  ...   4    4    3    3    4    4    4    4    1    1  
910           4        0  ...   2    5    4    3    ?    5    5    5    4    1  
911           2        0  ...   5    1    5    2    2    4    4    2    1    1  
912           2        0  ...   3    3    ?    3    3    2    3    3    1    1  

[350 rows x 53 columns]

In [34]:
data1.columns

Index(['AGE', 'GENDER', 'DOMAIN', 'PhD', 'YEARSEXP', 'UNIVERSITY',
       'UOC_POSITION', 'OTHER_POSITION', 'OTHERSTATUS', 'USERWIKI', 'PU1',
       'PU2', 'PU3', 'PEU1', 'PEU2', 'PEU3', 'ENJ1', 'ENJ2', 'Qu1', 'Qu2',
       'Qu3', 'Qu4', 'Qu5', 'Vis1', 'Vis2', 'Vis3', 'Im1', 'Im2', 'Im3', 'SA1',
       'SA2', 'SA3', 'Use1', 'Use2', 'Use3', 'Use4', 'Use5', 'Pf1', 'Pf2',
       'Pf3', 'JR1', 'JR2', 'BI1', 'BI2', 'Inc1', 'Inc2', 'Inc3', 'Inc4',
       'Exp1', 'Exp2', 'Exp3', 'Exp4', 'Exp5'],
      dtype='object')

In [35]:
data1['DOMAIN'].replace('?',np.nan,inplace=True)

In [32]:
data1['UOC_POSITION'].replace("?",np.nan,inplace=True)

In [33]:
data1['OTHERSTATUS'].replace('?',np.nan,inplace=True)

In [37]:
data1['YEARSEXP'].replace('?',np.nan,inplace=True)

In [38]:
data1['OTHER_POSITION'].replace('?',np.nan,inplace=True)

In [39]:
data1['USERWIKI'].replace('?',np.nan,inplace=True)

In [40]:
data1['PU1'].replace('?',np.nan,inplace=True)

In [41]:
data1['PU2'].replace('?',np.nan,inplace=True)

In [42]:
data1['PU3'].replace('?',np.nan,inplace=True)

In [43]:
data1['PEU1'].replace('?',np.nan,inplace=True)

In [44]:
data1['PEU2'].replace('?',np.nan,inplace=True)

In [45]:
data1['PEU3'].replace('?',np.nan,inplace=True)

In [46]:
data1['ENJ1'].replace('?',np.nan,inplace=True)

In [47]:
data1['ENJ2'].replace('?',np.nan,inplace=True)

In [48]:
data1['Qu1'].replace('?',np.nan,inplace=True)

In [49]:
data1['Qu2'].replace('?',np.nan,inplace=True)

In [50]:
data1['Qu3'].replace('?',np.nan,inplace=True)

In [51]:
data1['Qu4'].replace('?',np.nan,inplace=True)

In [52]:
data1['Qu5'].replace('?',np.nan,inplace=True)

In [53]:
data1['Vis1'].replace('?',np.nan,inplace=True)

In [54]:
data1['Vis2'].replace('?',np.nan,inplace=True)

In [55]:
data1['Vis3'].replace('?',np.nan,inplace=True)

In [56]:
data1['Im1'].replace('?',np.nan,inplace=True)

In [57]:
data1['Im2'].replace('?',np.nan,inplace=True)

In [58]:
data1['Im3'].replace('?',np.nan,inplace=True)

In [59]:
data1['SA1'].replace('?',np.nan,inplace=True)

In [60]:
data1['SA2'].replace('?',np.nan,inplace=True)

In [61]:
data1['SA3'].replace('?',np.nan,inplace=True)

In [62]:
data1['Use1'].replace('?',np.nan,inplace=True)

In [63]:
data1['Use2'].replace('?',np.nan,inplace=True)

In [64]:
data1['Use3'].replace('?',np.nan,inplace=True)

In [65]:
data1['Use4'].replace('?',np.nan,inplace=True)

In [66]:
data1['Use5'].replace('?',np.nan,inplace=True)

In [67]:
data1['Pf1'].replace('?',np.nan,inplace=True)

In [68]:
data1['Pf2'].replace('?',np.nan,inplace=True)

In [69]:
data1['Pf3'].replace('?',np.nan,inplace=True)

In [70]:
data1['JR1'].replace('?',np.nan,inplace=True)

In [71]:
data1['JR2'].replace('?',np.nan,inplace=True)

In [72]:
data1['BI1'].replace('?',np.nan,inplace=True)

In [73]:
data1['BI2'].replace('?',np.nan,inplace=True)

In [74]:
data1['Inc1'].replace('?',np.nan,inplace=True)

In [75]:
data1['Inc2'].replace('?',np.nan,inplace=True)

In [76]:
data1['Inc3'].replace('?',np.nan,inplace=True)

In [77]:
data1['Inc4'].replace('?',np.nan,inplace=True)

In [78]:
data1['Exp1'].replace('?',np.nan,inplace=True)

In [79]:
data1['Exp2'].replace('?',np.nan,inplace=True)

In [80]:
data1['Exp3'].replace('?',np.nan,inplace=True)

In [81]:
data1['Exp3'].replace('?',np.nan,inplace=True)

In [82]:
data1['Exp4'].replace('?',np.nan,inplace=True)

In [83]:
data1['Exp5'].replace('?',np.nan,inplace=True)

In [84]:
data1

AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION OTHER_POSITION  \
0     40       0      2    1       14           1            2            NaN   
1     42       0      5    1       18           1            2            NaN   
2     37       0      4    1       13           1            3            NaN   
3     40       0      4    0       13           1            3            NaN   
4     51       0      6    0        8           1            3            NaN   
..   ...     ...    ...  ...      ...         ...          ...            ...   
908   43       0      5    1       21           2          NaN            NaN   
909   53       0      6    0       25           2          NaN            NaN   
910   39       0      5    1        9           2          NaN            NaN   
911   40       0      3    1       10           2          NaN            NaN   
912   41       1      3    1       12           2          NaN            NaN   

    OTHERSTATUS USERWIKI  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3 Exp4 Exp5  
0           NaN        0  ...   3    5    5    5    5    4    4    4    1    2  
1           NaN        0  ...   2    4    4    3    4    2    2    4    2    4  
2           NaN        0  ...   1    5    3    5    5    2    2    2    1    3  
3           NaN        0  ...   3    3    4    4    3    4    4    3    3    4  
4           NaN        1  ...   5    5    5    4    4    5    5    5    4    4  
..          ...      ...  ...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  
908           2        0  ...   2    2    2    2    2  NaN  NaN  NaN  NaN  NaN  
909           6        0  ...   4    4    3    3    4    4    4    4    1    1  
910           4        0  ...   2    5    4    3  NaN    5    5    5    4    1  
911           2        0  ...   5    1    5    2    2    4    4    2    1    1  
912           2        0  ...   3    3  NaN    3    3    2    3    3    1    1  

[913 rows x 53 columns]

In [94]:
pandas_profiling.ProfileReport(data1)

/home/manikanta/.local/lib/python3.6/site-packages/pandas_profiling/model/correlations.py:126: UserWarning: There was an attempt to calculate the cramers correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"cramers": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/pandas-profiling/pandas-profiling/issues
(include the error message: 'The internally computed table of expected frequencies has a zero element at (0, 28).')
  correlation_name=correlation_name, error=error


In [95]:
data1.isna().sum()

AGE                 0
GENDER              0
DOMAIN              2
PhD                 0
YEARSEXP           23
UNIVERSITY          0
UOC_POSITION      113
OTHER_POSITION    261
OTHERSTATUS       540
USERWIKI            4
PU1                 7
PU2                11
PU3                 5
PEU1                4
PEU2               14
PEU3               97
ENJ1                7
ENJ2               17
Qu1                 7
Qu2                10
Qu3                15
Qu4                22
Qu5                29
Vis1               72
Vis2              117
Vis3                8
Im1                22
Im2                20
Im3                57
SA1                11
SA2                12
SA3                11
Use1               14
Use2               17
Use3                9
Use4               23
Use5               15
Pf1                11
Pf2                 6
Pf3                14
JR1                27
JR2                53
BI1                32
BI2                43
Inc1               35
Inc2      

In [123]:
x=data1.fillna(method='bfill')

In [124]:
x

AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION OTHER_POSITION  \
0     40       0      2    1       14           1            2              2   
1     42       0      5    1       18           1            2              2   
2     37       0      4    1       13           1            3              2   
3     40       0      4    0       13           1            3              2   
4     51       0      6    0        8           1            3              2   
..   ...     ...    ...  ...      ...         ...          ...            ...   
908   43       0      5    1       21           2          NaN            NaN   
909   53       0      6    0       25           2          NaN            NaN   
910   39       0      5    1        9           2          NaN            NaN   
911   40       0      3    1       10           2          NaN            NaN   
912   41       1      3    1       12           2          NaN            NaN   

    OTHERSTATUS USERWIKI  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3 Exp4 Exp5  
0             7        0  ...   3    5    5    5    5    4    4    4    1    2  
1             7        0  ...   2    4    4    3    4    2    2    4    2    4  
2             7        0  ...   1    5    3    5    5    2    2    2    1    3  
3             7        0  ...   3    3    4    4    3    4    4    3    3    4  
4             7        1  ...   5    5    5    4    4    5    5    5    4    4  
..          ...      ...  ...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  
908           2        0  ...   2    2    2    2    2    4    4    4    1    1  
909           6        0  ...   4    4    3    3    4    4    4    4    1    1  
910           4        0  ...   2    5    4    3    2    5    5    5    4    1  
911           2        0  ...   5    1    5    2    2    4    4    2    1    1  
912           2        0  ...   3    3  NaN    3    3    2    3    3    1    1  

[913 rows x 53 columns]

In [125]:
data2=x.fillna(0)

In [126]:
data2

AGE  GENDER DOMAIN  PhD YEARSEXP  UNIVERSITY UOC_POSITION OTHER_POSITION  \
0     40       0      2    1       14           1            2              2   
1     42       0      5    1       18           1            2              2   
2     37       0      4    1       13           1            3              2   
3     40       0      4    0       13           1            3              2   
4     51       0      6    0        8           1            3              2   
..   ...     ...    ...  ...      ...         ...          ...            ...   
908   43       0      5    1       21           2            0              0   
909   53       0      6    0       25           2            0              0   
910   39       0      5    1        9           2            0              0   
911   40       0      3    1       10           2            0              0   
912   41       1      3    1       12           2            0              0   

    OTHERSTATUS USERWIKI  ... BI2 Inc1 Inc2 Inc3 Inc4 Exp1 Exp2 Exp3 Exp4 Exp5  
0             7        0  ...   3    5    5    5    5    4    4    4    1    2  
1             7        0  ...   2    4    4    3    4    2    2    4    2    4  
2             7        0  ...   1    5    3    5    5    2    2    2    1    3  
3             7        0  ...   3    3    4    4    3    4    4    3    3    4  
4             7        1  ...   5    5    5    4    4    5    5    5    4    4  
..          ...      ...  ...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  
908           2        0  ...   2    2    2    2    2    4    4    4    1    1  
909           6        0  ...   4    4    3    3    4    4    4    4    1    1  
910           4        0  ...   2    5    4    3    2    5    5    5    4    1  
911           2        0  ...   5    1    5    2    2    4    4    2    1    1  
912           2        0  ...   3    3    0    3    3    2    3    3    1    1  

[913 rows x 53 columns]

In [127]:
data2.isna().sum()

AGE               0
GENDER            0
DOMAIN            0
PhD               0
YEARSEXP          0
UNIVERSITY        0
UOC_POSITION      0
OTHER_POSITION    0
OTHERSTATUS       0
USERWIKI          0
PU1               0
PU2               0
PU3               0
PEU1              0
PEU2              0
PEU3              0
ENJ1              0
ENJ2              0
Qu1               0
Qu2               0
Qu3               0
Qu4               0
Qu5               0
Vis1              0
Vis2              0
Vis3              0
Im1               0
Im2               0
Im3               0
SA1               0
SA2               0
SA3               0
Use1              0
Use2              0
Use3              0
Use4              0
Use5              0
Pf1               0
Pf2               0
Pf3               0
JR1               0
JR2               0
BI1               0
BI2               0
Inc1              0
Inc2              0
Inc3              0
Inc4              0
Exp1              0
Exp2              0


In [128]:
#model
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.20)

In [129]:
lr=LinearRegression(normalize=True)
lr.fit(x_data,y_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [130]:
train_score=lr.score(x_train,y_train)
train_score

0.41335360324380716

In [131]:
test_score=lr.score(x_test,y_test)
test_score

0.4591700343614566

In [132]:
x_train.shape

(730, 52)

In [133]:
x_test.shape

(183, 52)

In [134]:
y_train.shape

(730, 1)

In [135]:
y_test.shape

(183, 1)

In [136]:
new_prediction=lr.predict(x_test)
new_prediction

array([[39.61292901],
       [39.86131707],
       [36.55696974],
       [34.10294681],
       [44.23357109],
       [38.01688332],
       [42.3379918 ],
       [42.99981573],
       [43.47251195],
       [40.36748966],
       [45.03723393],
       [50.13465794],
       [41.9591506 ],
       [36.04641903],
       [35.67740714],
       [45.38405206],
       [40.17273545],
       [50.64499433],
       [60.28710856],
       [37.38895416],
       [38.69141317],
       [46.27929282],
       [39.84248287],
       [47.2213471 ],
       [46.43834575],
       [49.47621787],
       [44.50433673],
       [47.07159471],
       [50.7967348 ],
       [39.22326988],
       [39.00602848],
       [39.23112222],
       [40.52385769],
       [48.13986732],
       [43.06533782],
       [49.06913145],
       [56.37782871],
       [49.02780816],
       [28.57669475],
       [45.4095713 ],
       [49.16158942],
       [42.93879737],
       [35.47537124],
       [48.66605544],
       [38.07976172],
       [42

In [174]:
x1=({'new_pre':new_prediction,'actual_data':y_test})
x2=pd.DataFrame([x1])

In [163]:
#x1=({'new_pre':new_prediction,'actual_data':y_test})


In [164]:
mean_squared_error(new_prediction,y_test)

33.87421445207088

In [165]:
mean_absolute_error(new_prediction,y_test)

4.472635445083116

In [166]:
##model score
r2_score(new_prediction,y_test)

-0.11161827365887622

In [167]:
from sklearn.model_selection import cross_val_score

In [168]:
cv=cross_val_score(lr,x_train,y_train,cv=20)

In [169]:
cv

array([0.26918528, 0.28007337, 0.42338659, 0.18036468, 0.36620215,
       0.25412896, 0.57618305, 0.19880138, 0.21261823, 0.30693038,
       0.49189724, 0.1491952 , 0.27131729, 0.33461157, 0.2082132 ,
       0.48704898, 0.20317933, 0.41310829, 0.15169422, 0.2891704 ])

In [170]:
np.mean(cv)

0.30336548889120846

In [171]:
np.max(cv)

0.5761830519918959

In [172]:
np.min(cv)

0.1491951961084892

In [176]:
pandas_profiling.ProfileReport(data2)

In [ ]:
sns.pairplot(data2)