In [2]:
import numpy as np
import pandas as pd
import scipy as stats
import seaborn as sns
import pandas_profiling
import matplotlib  as plt


import numpy
from sklearn import linear_model
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
import statistics as stat
from sklearn.model_selection import train_test_split

In [3]:
iris=datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
x=iris.data[:,[0,2]]
y=iris.target

In [5]:
print(x.shape)
print(y.shape)

(150, 2)
(150,)


In [7]:
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)

In [10]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(112, 2)
(112,)
(38, 2)
(38,)


In [11]:
# A simple average ensemble model
model1 = DecisionTreeClassifier(max_depth=4)
model2 = KNeighborsClassifier(n_neighbors=7)
model3 = SVC(kernel='rbf',probability=True)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

#pred1=model1.predict(x_test)
#pred2=model2.predict(x_test)
#pred3=model3.predict(x_test)

In [33]:
# lets look at the accuracy for each model
score1=model1.score(x_test,y_test)
print(score1)

0.9736842105263158


In [34]:
score2=model2.score(x_test,y_test)
print(score1)

0.9736842105263158


In [35]:
score3=model3.score(x_test,y_test)
print(score1)

0.9736842105263158


In [18]:
# prediciton process
pred1=model1.predict(x_test)
pred2=model2.predict(x_test)
pred3=model3.predict(x_test)

In [20]:
final_pred=np.array([])
for i in range(0,len(x_test)):
    final_pred=np.append(final_pred,stat.mode([pred1[i],
                                              pred2[i],
                                              pred3[i]]))
final_pred

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 2., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

In [22]:
total=np.sum(y_test==final_pred)
print("accuracy",total,"/",len(final_pred),"*100=","{0:.3f}".format(total/len(final_pred)*100),"%")

accuracy 37 / 38 *100= 97.368 %


In [28]:
#soft voting in python
spred1=model1.predict_proba(x_test)
spred2=model2.predict_proba(x_test)
spred3=model3.predict_proba(x_test)
finalpred=(spred1+spred2+spred3)/3
finalpred

array([[0.98900719, 0.00557362, 0.00541919],
       [0.05676041, 0.93374976, 0.00948983],
       [0.00515311, 0.98626028, 0.00858662],
       [0.99078734, 0.00522379, 0.00398886],
       [0.00860227, 0.0182068 , 0.97319093],
       [0.0042457 , 0.7691791 , 0.22657519],
       [0.00664781, 0.27731973, 0.71603246],
       [0.97510544, 0.01993641, 0.00495815],
       [0.98423522, 0.01127224, 0.00449254],
       [0.00405535, 0.00859005, 0.9873546 ],
       [0.00277927, 0.97866289, 0.01855784],
       [0.98399819, 0.01158933, 0.00441248],
       [0.00438769, 0.00698474, 0.98862757],
       [0.00402316, 0.97421861, 0.02175823],
       [0.00307901, 0.90308786, 0.09383313],
       [0.9857468 , 0.00867448, 0.00557873],
       [0.0035773 , 0.99221212, 0.00421057],
       [0.00326255, 0.85603843, 0.14069902],
       [0.98866777, 0.00732083, 0.00401139],
       [0.99123034, 0.00484928, 0.00392038],
       [0.00311911, 0.92967947, 0.06720141],
       [0.00352241, 0.77791891, 0.21855868],
       [0.

In [29]:
final_class=finalpred.argmax(axis=-1)
final_class


array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [30]:
# we can applay for the volting process
emodel=VotingClassifier(estimators=[('dt',model1),('knn',model2),('svc',model3)],voting='soft')
emodel.fit(x_train,y_train)

VotingClassifier(estimators=[('dt',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=4,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_state=None,
      

In [31]:
#accuracy score for the ensemble modelis
escore=emodel.score(x_test,y_test)
print(escore)

0.9736842105263158


In [32]:
emodel.classes_

array([0, 1, 2])